# Generated by Django 3.1.3 on 2021-03-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20210302_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='usage_type',
            field=models.CharField(choices=[('single', 'Использовать можно один раз'), ('multiple', 'Использовать можно множество раз')], default='single', max_length=50),
        ),
    ]
