# Generated by Django 3.1.3 on 2021-03-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_ves'),
        ('cart', '0017_coupon_usage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(to='products.Category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_type',
            field=models.CharField(choices=[('single', 'Один раз на каждого пользователя'), ('multiple', 'Множество раз на каждого')], default='single', max_length=50),
        ),
    ]
