# Generated by Django 3.1.3 on 2021-03-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_auto_20210302_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='description',
        ),
    ]
