# Generated by Django 3.1.3 on 2021-03-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_auto_20210302_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='from_amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
