# Generated by Django 3.1.3 on 2021-03-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
