# Generated by Django 3.1.3 on 2021-03-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210227_1414'),
        ('cart', '0027_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='users',
            field=models.ManyToManyField(to='users.User'),
        ),
    ]
