# Generated by Django 3.1.3 on 2021-03-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_coupon_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
