# Generated by Django 3.1.3 on 2021-03-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210227_1414'),
        ('cart', '0029_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='users.User'),
        ),
    ]
