# Generated by Django 3.1.3 on 2021-03-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0031_cart_bonus_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='bonus_used',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
