# Generated by Django 3.1.3 on 2021-03-23 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20210306_1510'),
        ('cart', '0034_order_bonus_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
    ]
