# Generated by Django 3.1.3 on 2021-03-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0038_auto_20210323_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='imgsrc',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pr_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sale_price',
        ),
    ]
