# Generated by Django 3.1.3 on 2021-03-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0039_auto_20210323_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('courier', 'Доставка курьером'), ('byclient', 'Самовывоз')], default='courier', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cart', 'Картой курьеру'), ('cash', 'Наличными')], default='cash', max_length=200),
        ),
    ]
