# Generated by Django 3.1.3 on 2021-03-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0040_auto_20210324_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
