# Generated by Django 3.1.3 on 2021-03-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0041_auto_20210324_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_discount_use',
            field=models.BooleanField(default=False),
        ),
    ]
