# Generated by Django 3.1.3 on 2021-03-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0043_auto_20210325_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_discount_use',
            field=models.BooleanField(default=False),
        ),
    ]
