# Generated by Django 3.1.3 on 2021-03-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20210326_1405'),
        ('cart', '0044_order_delivery_discount_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET, to='products.product'),
        ),
    ]
