# Generated by Django 3.1.3 on 2021-03-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0047_order_delivery_bonus_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_bonus_use',
            new_name='user_append_bonus',
        ),
    ]
