# Generated by Django 3.1.3 on 2021-03-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0048_auto_20210326_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='current_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='current_phone',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
