# Generated by Django 3.1.3 on 2021-03-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0049_auto_20210331_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='current_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='current_phone',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
