# Generated by Django 3.1.3 on 2021-03-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0050_auto_20210331_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='current_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='current_phone',
        ),
    ]
