# Generated by Django 3.0.8 on 2020-11-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('description', models.CharField(default='', max_length=2000)),
                ('imgsrc', models.ImageField(upload_to='static/images/stock')),
            ],
        ),
    ]
