# Generated by Django 3.0.8 on 2020-11-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgsrc',
            field=models.ImageField(upload_to='static/images/products'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='imgsrc',
            field=models.ImageField(upload_to='static/images/products'),
        ),
    ]
