# Generated by Django 3.0.8 on 2020-11-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20201103_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='destination',
        ),
    ]
