# Generated by Django 3.0.8 on 2020-11-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imgsrc',
            field=models.ImageField(default=None, upload_to='static/images/products'),
        ),
    ]
