# Generated by Django 3.0.8 on 2020-11-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_category_imgsrc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeitem',
            name='attr',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Attributeitem',
        ),
    ]
