# Generated by Django 3.0.8 on 2020-11-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_delete_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imgsrc',
            field=models.ImageField(upload_to='static/images/products'),
        ),
    ]
