# Generated by Django 3.0.8 on 2020-11-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20201104_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imgsrc',
        ),
    ]
