# Generated by Django 3.0.8 on 2020-11-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_product_imgsrc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='imgsrc',
        ),
        migrations.AddField(
            model_name='product',
            name='imgsrc',
            field=models.ImageField(default='', upload_to='static/images/products'),
        ),
    ]
