# Generated by Django 3.0.8 on 2020-11-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20201104_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imgsrc',
            field=models.ImageField(default='', upload_to='static/images/products'),
        ),
    ]
