# Generated by Django 3.1.3 on 2020-11-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_category_imgsrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ves',
            field=models.CharField(default='', max_length=300),
        ),
    ]
