# Generated by Django 3.1.3 on 2021-03-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_ves'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imgname',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='imgname',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
