# Generated by Django 3.1.3 on 2021-03-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20210326_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_priority',
            field=models.IntegerField(default=0),
        ),
    ]
