# Generated by Django 3.1.3 on 2021-03-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_category_display_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='display_priority',
            field=models.IntegerField(default=0),
        ),
    ]
