# Generated by Django 3.1.3 on 2021-03-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_stock_display_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_priority',
            field=models.IntegerField(default=0),
        ),
    ]
